"""New Migration

Revision ID: 7670546afac2
Revises: 6cdded134f80
Create Date: 2022-07-22 13:38:07.328446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7670546afac2'
down_revision = '6cdded134f80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
